from tkinter import*
m=Tk()
m.geometry("390x400")
m.title("Billing")
Label(m,text="Name: ").grid(row=0,column=0,padx=10)
Entry(m,width=30).grid(row=0,column=1)
Label(m,text="Products:").grid(row=1,column=0,padx=10,sticky=S)
a= Text(m,height=6,width=23)
a.insert(INSERT,"Items             Price\n\nPen                10/-\nPencil             5/-\nEraser             10/-\nSharpener          15/-")
a.grid(row=1,column=1,padx=50,rowspan=7,pady=10)
Label(m,text="Quantity: ").grid(row=8,column=0)
Entry(m,width=30).grid(row=8,column=1,pady=10,padx=10)
Button(m,text="Add Items",width=15).place(x=197,y=180)
Text(m,height=6,width=30).place(x=70,y=220)
Button(m,text="Clear Items",width=15).place(x=59,y=330)
Button(m,text="Total",width=15).place(x=210,y=330)
m.mainloop()
