from tkinter import*
from tkinter import ttk
#Program15: Python GUI
m=Tk()
m.geometry("450x400")
m.title("Python GUI")
menubar= Menu(m,background='#ff8000', foreground='black', activebackground='white', activeforeground='black')
file = Menu(menubar,tearoff=1,foreground='black')
file.add_command(label="New")
file.add_command(label="Open")
file.add_command(label="Save")
file.add_command(label="Save as")
file.add_separator()
file.add_command(label="Exit",command=m.quit)
menubar.add_cascade(label="File",menu=file)
help = Menu(menubar, tearoff=0)
menubar.add_cascade(label="Help", menu=help)
help = Menu(menubar, tearoff=0)
m.config(menu=menubar)
tabControl= ttk.Notebook(m)
tab1=Frame(tabControl)
tab2=Frame(tabControl)
tabControl.add(tab1, text='Tab 1')
tabControl.add(tab2, text='Tab 2')
tabControl.pack(expand=1, fill="both")
Label(tab1,text="Krishna Chaitanya Thota \n\nRA2011003010340").grid(row=1,column=0,padx=30,pady=30)
Label(tab2,text="The Snake",fg="blue").grid(row=0,column=0,padx=20,pady=10,sticky=W)
Checkbutton(tab2,text="Disabled").grid(row=1,column=0,padx=30,pady=10)
Checkbutton(tab2,text="UnChecked").grid(row=1,column=1,padx=20,pady=10)
Checkbutton(tab2,text="Enabled").grid(row=1,column=2,padx=10,pady=10)
t=IntVar()
Radiobutton(tab2,text="Blue",variable=t,value="Blue").place(x=30,y=97)
Radiobutton(tab2,text="Gold",variable=t,value="Gold").place(x=153,y=97)
Radiobutton(tab2,text="Red",variable=t,value="Red").place(x=272,y=97)
Label(tab2,text="ProgressBar",fg="blue").place(x=40,y=137)
a=Button(tab2,text="Run Progressbar",width=15).place(x=38,y=162)
b=Button(tab2,text="Stop Progressbar",width=15).place(x=38,y=192)
c=Button(tab2,text="Stop immediately",width=15).place(x=38,y=222)
d=Button(tab2,text="Stop after second",width=15).place(x=38,y=252)
pb= ttk.Progressbar(tab2,orient='horizontal',length=393)
pb['value']=40
pb.place(x=28,y=300)
m.mainloop()